name: MCTag
version: 0.5
main: me.hawkfalcon.mctag.MCTag
commands:
    Tag:
        description: Makes you it
        usage: /tag
        
    Tagend:
        description: Ends the game of tag
        usage: /tagend
permissions: 
    MCTag.Tag:
        description: Allows use of /tag
        default: OP
        
    MCTag.Tagend:
        description: Allows use of /tagend
        default: OP