name: MCTag
version: 0.5
main: me.hawkfalcon.mctag.MCTag
commands:
    Tag:
       description: All the MCTag commands
       usage: /tag [start|stop|tagback (allow|forbid)]
   
permissions: 
    MCTag.start:
        description: Allows use of /tag start
        default: OP
        
    MCTag.stop:
        description: Allows use of /tag stop
        default: OP
        
    MCTag.tagbackallow:
        description: Allows use of /tag tagback allow
        default: OP
        
    MCTag.tagbackforbid:
        description: Allows use of /tag tagback forbid
        default: OP